server:
  port: 8080
  servlet:
    context-path: /cms

spring:
  security:
    enabled: false
    user:
      name: cms
      password: cms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qdd-foods?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root1012
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-request-size: 80MB
      max-file-size: 80MB
  redis:
    # host: 127.0.0.1
    port: 6379
    ssl: true
    password: ""


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
